# Generated by Django 4.0.8 on 2023-12-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['drug_bankID__name']},
        ),
    ]
