# Generated by Django 4.0.8 on 2024-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_alter_interaction_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['drug_bankID'], name='interaction_drug_ba_f8f241_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['uniprot_ID'], name='interaction_uniprot_d7864d_idx'),
        ),
    ]
