# Generated by Django 4.0.8 on 2024-01-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_interaction_interaction_drug_ba_f8f241_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interaction',
            name='interaction_drug_ba_f8f241_idx',
        ),
    ]
