# Generated by Django 4.0.8 on 2023-12-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chromosome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chromosome',
            old_name='ensemble',
            new_name='ensembl',
        ),
    ]
