# Generated by Django 4.0.8 on 2024-01-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chromosome', '0002_rename_ensemble_chromosome_ensembl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chromosome',
            old_name='refseg',
            new_name='refseq',
        ),
    ]
