# Generated by Django 4.0.8 on 2023-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0005_alter_genebassvariant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vepvariant',
            name='AM_pathogenicity',
            field=models.FloatField(null=True),
        ),
    ]
