# Generated by Django 4.0.8 on 2023-12-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0006_vepvariant_am_pathogenicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugPhenocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_description', models.TextField(null=True)),
                ('drugname_in_coding_description', models.CharField(max_length=100, null=True)),
                ('phenocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variantphenocode')),
            ],
        ),
    ]
