# Generated by Django 4.0.8 on 2023-12-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_alter_atcanatomicalgroup_options_and_more'),
        ('variant', '0008_genebasspgx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenebassVariantPGx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genename', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=100)),
                ('n_cases', models.FloatField()),
                ('n_controls', models.FloatField()),
                ('coding_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('AC', models.FloatField()),
                ('AF', models.FloatField()),
                ('Pvalue', models.FloatField()),
                ('BETA', models.FloatField()),
                ('drugbank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
                ('phenocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variant.variantphenocode')),
                ('variant_marker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variant.variant')),
            ],
        ),
    ]
