# Generated by Django 4.2.7 on 2023-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0008_genebasspgx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genebasspgx',
            name='annotation',
            field=models.CharField(max_length=100),
        ),
    ]
