# Generated by Django 4.0.8 on 2023-12-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_gene_primary_transcript'),
        ('drug', '0003_alter_atcanatomicalgroup_options_and_more'),
        ('variant', '0009_genebassvariantpgx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmgkb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariantAnnotationID', models.CharField(max_length=100)),
                ('Variant_or_Haplotypes', models.CharField(max_length=100)),
                ('PMID', models.CharField(max_length=100)),
                ('Phenotype_Category', models.CharField(max_length=100)),
                ('Significance', models.CharField(max_length=100)),
                ('Notes', models.TextField()),
                ('Sentence', models.TextField()),
                ('Alleles', models.CharField(max_length=100)),
                ('P_Value', models.CharField(max_length=100)),
                ('Biogeographical_Groups', models.CharField(max_length=100)),
                ('Study_Type', models.CharField(max_length=100)),
                ('Study_Cases', models.FloatField()),
                ('Study_ontrols', models.FloatField()),
                ('Direction_of_effect', models.CharField(max_length=100)),
                ('PD_PK_terms', models.CharField(max_length=100)),
                ('Metabolizer_types', models.CharField(max_length=100)),
                ('drugbank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
                ('geneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gene.gene')),
            ],
        ),
    ]
