# Generated by Django 4.0.8 on 2023-12-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0010_pharmgkb'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
