# Generated by Django 4.0.8 on 2023-12-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0010_pharmgkb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmgkb',
            old_name='Study_ontrols',
            new_name='Study_Controls',
        ),
    ]
