# Generated by Django 4.0.8 on 2024-01-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0011_variantstatistics'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genebassvariantpgx',
            index=models.Index(fields=['drugbank_id'], name='variant_gen_drugban_6cc56b_idx'),
        ),
        migrations.AddIndex(
            model_name='genebassvariantpgx',
            index=models.Index(fields=['genename'], name='variant_gen_genenam_6234ce_idx'),
        ),
    ]
