# Generated by Django 4.0.8 on 2023-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0011_rename_study_ontrols_pharmgkb_study_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmgkb',
            name='Variant_or_Haplotypes',
            field=models.TextField(),
        ),
    ]
