# Generated by Django 4.0.8 on 2023-12-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0012_alter_pharmgkb_variant_or_haplotypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmgkb',
            name='Alleles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='Biogeographical_Groups',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='Direction_of_effect',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='Metabolizer_types',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='PD_PK_terms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='Phenotype_Category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='Significance',
            field=models.TextField(),
        ),
    ]
