# Generated by Django 4.0.8 on 2024-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0012_genebassvariantpgx_variant_gen_drugban_6cc56b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vepvariant',
            index=models.Index(fields=['Transcript_ID'], name='variant_vep_Transcr_e3589f_idx'),
        ),
        migrations.AddIndex(
            model_name='vepvariant',
            index=models.Index(fields=['Variant_marker'], name='variant_vep_Variant_a4d9e4_idx'),
        ),
    ]
