# Generated by Django 4.0.8 on 2024-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0013_vepvariant_variant_vep_transcr_e3589f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmgkb',
            name='P_Value_numeric',
            field=models.FloatField(null=True),
        ),
    ]
