# Generated by Django 4.0.8 on 2024-02-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0014_pharmgkb_p_value_numeric'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_version', models.CharField(max_length=50)),
                ('ensembl', models.CharField(max_length=50)),
                ('refseq', models.CharField(max_length=50)),
            ],
        ),
    ]
