# Generated by Django 4.0.8 on 2024-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0015_variantmapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='vepvariant',
            name='HighestAF',
            field=models.FloatField(null=True),
        ),
    ]
