# Generated by Django 4.0.8 on 2023-12-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_drug_clinical_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atcanatomicalgroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='atcchemicalgroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='atcchemicalsubstance',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='atcpharmacologicalgroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='atctherapeuticgroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('drug_bankID',)},
        ),
    ]
