# Generated by Django 4.0.8 on 2024-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_alter_atcanatomicalgroup_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drugatcassociation',
            index=models.Index(fields=['atc_id'], name='drug_atc_as_atc_id__e28238_idx'),
        ),
        migrations.AddIndex(
            model_name='drugatcassociation',
            index=models.Index(fields=['drug_id'], name='drug_atc_as_drug_id_8048fd_idx'),
        ),
    ]
