# Generated by Django 4.0.8 on 2024-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_drugatcassociation_drug_atc_as_atc_id__e28238_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['drug_bankID'], name='drug_drug_drug_ba_1550a5_idx'),
        ),
    ]
