# Generated by Django 4.0.8 on 2024-05-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0005_drug_drug_drug_drug_ba_1550a5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseDrugReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_data', models.TextField(default='None')),
                ('drug_bankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
            ],
        ),
    ]
