# Generated by Django 4.0.8 on 2024-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0006_adversedrugreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('side_effect_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('side_effect_definition', models.TextField()),
            ],
        ),
    ]
