# Generated by Django 4.0.8 on 2024-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0007_sideeffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCachedDrugNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atc_code', models.CharField(max_length=7)),
                ('json_data', models.TextField(default='')),
            ],
        ),
    ]
