# Generated by Django 4.0.8 on 2024-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0008_precacheddrugnetwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precacheddrugnetwork',
            old_name='json_data',
            new_name='drug_json_data',
        ),
        migrations.AddField(
            model_name='precacheddrugnetwork',
            name='general_json_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='precacheddrugnetwork',
            name='interaction_json_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='precacheddrugnetwork',
            name='protein_json_data',
            field=models.TextField(default=''),
        ),
    ]
