# Generated by Django 4.0.8 on 2024-01-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0003_alter_atcanatomicalgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease_name', models.CharField(max_length=100)),
                ('Disease_class', models.CharField(max_length=100)),
                ('Merged_RefNew', models.CharField(max_length=255)),
                ('CID', models.CharField(max_length=25)),
                ('Standard_inchiKey', models.TextField()),
                ('Disease_UML_CUI', models.CharField(max_length=255)),
                ('drug_bankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
            ],
        ),
    ]
