# Generated by Django 4.0.8 on 2024-01-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0003_alter_atcanatomicalgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_class', models.CharField(max_length=100)),
                ('disease_UML_CUI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrugDiseaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('standard_inchiKey', models.TextField()),
                ('clinical_trial', models.CharField(max_length=10)),
                ('disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
                ('drug_bankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
            ],
        ),
    ]
