# Generated by Django 4.0.8 on 2024-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drugdiseasestudy',
            index=models.Index(fields=['drug_bankID'], name='disease_dru_drug_ba_458e33_idx'),
        ),
        migrations.AddIndex(
            model_name='drugdiseasestudy',
            index=models.Index(fields=['disease_name'], name='disease_dru_disease_9bf3d2_idx'),
        ),
    ]
