# Generated by Django 4.0.8 on 2023-12-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0008_protein_protein_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protein',
            options={'ordering': ('uniprot_ID',)},
        ),
    ]
